# Generated by Django 4.0.3 on 2022-03-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0002_rename_сandies_candy_rename_сandyamount_candyamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
