# Generated by Django 4.0.3 on 2022-03-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0003_alter_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
