# Generated by Django 4.0.3 on 2022-03-11 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candy', '0007_alter_orders_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candies', to='candy.category'),
        ),
        migrations.AlterField(
            model_name='candyamount',
            name='candy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candy_amounts', to='candy.candy'),
        ),
        migrations.AlterField(
            model_name='candyamount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candy_amounts', to='candy.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
